/**
 * Copyright (c) 2026 Yanis Sebastian Zürcher
 *
 * Writes src/config/project-image-sizes.ts: the pixel size of every WebP
 * under public/projects, and the colour along its top. The deep-dive image
 * component puts the size on the <img> as width/height so the browser
 * reserves the right box before a lazy image loads. Without that a page grows
 * while you scroll it, and a jump to a section lands short of it.
 *
 * Run `bun run images:sizes` after adding or replacing a project image;
 * src/config/project-image-sizes.test.ts fails when the file is stale.
 */

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";

const ROOT = "public/projects";
const OUT = "src/config/project-image-sizes.ts";

/** Rows read from the top; the median of them is the colour. */
const BAND = 9;

export async function imageSize(path) {
  const { width, height } = await sharp(path).metadata();
  return [width, height];
}

/**
 * The colour along the top of an image, as `#rrggbb`.
 *
 * A device frame fills its screen with this, so the shot and the frame read as
 * one. The median of the top rows rather than the first one: a capture often
 * carries a stray border row, and one of those on its own is the wrong answer
 * by a mile.
 */
export async function topColor(path) {
  const [width, height] = await imageSize(path);
  const band = Math.min(BAND, height);
  const { data } = await sharp(path)
    .extract({ left: 0, top: 0, width, height: band })
    .removeAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const rows = [];
  for (let y = 0; y < band; y += 1) {
    let r = 0;
    let g = 0;
    let b = 0;
    for (let x = 0; x < width; x += 1) {
      const at = (y * width + x) * 3;
      r += data[at];
      g += data[at + 1];
      b += data[at + 2];
    }
    rows.push([r / width, g / width, b / width]);
  }

  const median = (channel) => {
    const sorted = rows.map((row) => row[channel]).sort((a, b) => a - b);
    return Math.round(sorted[Math.floor(sorted.length / 2)]);
  };
  const hex = (value) => value.toString(16).padStart(2, "0");
  return `#${hex(median(0))}${hex(median(1))}${hex(median(2))}`;
}

function walk(dir, visit) {
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, visit);
    else if (name.toLowerCase().endsWith(".webp"))
      visit("/" + full.replaceAll("\\", "/").replace(/^public\//, ""), full);
  }
}

/** `read` runs on every image at once; the result keeps the walk's order. */
async function gather(dir, read) {
  const pending = [];
  walk(dir, (src, full) => pending.push([src, read(full)]));
  const out = {};
  for (const [src, value] of pending) out[src] = await value;
  return out;
}

export const collect = (dir = ROOT) => gather(dir, imageSize);

export const collectTints = (dir = ROOT) => gather(dir, topColor);

if (
  process.argv[1]?.replaceAll("\\", "/").endsWith("scripts/image-sizes.mjs")
) {
  const sizes = await collect();
  const tints = await collectTints();
  const rows = Object.entries(sizes)
    .map(([src, [w, h]]) => `  ${JSON.stringify(src)}: [${w}, ${h}],`)
    .join("\n");
  const tintRows = Object.entries(tints)
    .map(([src, tint]) => `  ${JSON.stringify(src)}: "${tint}",`)
    .join("\n");
  writeFileSync(
    OUT,
    `/**
 * Copyright (c) 2026 Yanis Sebastian Zürcher
 *
 * Generated by scripts/image-sizes.mjs (bun run images:sizes). Do not edit.
 * Pixel sizes of the project images, so a lazy <img> reserves its box, and
 * the colour of each one's top row, which a device frame paints the strip
 * above the screenshot in so the two read as one screen.
 */

export const PROJECT_IMAGE_SIZES: Record<
  string,
  readonly [width: number, height: number]
> = {
${rows}
};

export const PROJECT_IMAGE_TINTS: Record<string, string> = {
${tintRows}
};
`,
  );
  console.log(
    `${OUT}: ${Object.keys(sizes).length} images, ${Object.keys(tints).length} tints`,
  );
}
