/**
 * Copyright (c) 2026 Yanis Sebastian Zürcher
 *
 * Writes src/config/project-image-sizes.ts: the pixel size of every PNG
 * under public/projects, read from the file header. The deep-dive image
 * component puts those on the <img> as width/height so the browser reserves
 * the right box before a lazy image loads. Without that a page grows while
 * you scroll it, and a jump to a section lands short of it.
 *
 * Run `bun run images:sizes` after adding or replacing a project image;
 * src/config/project-image-sizes.test.ts fails when the file is stale.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = "public/projects";
const OUT = "src/config/project-image-sizes.ts";

/** A PNG stores its width and height big-endian at bytes 16 and 20 (IHDR). */
export function pngSize(path) {
  const buf = readFileSync(path);
  if (buf.toString("ascii", 1, 4) !== "PNG")
    throw new Error(`${path} is not a PNG`);
  return [buf.readUInt32BE(16), buf.readUInt32BE(20)];
}

export function collect(dir = ROOT) {
  const sizes = {};
  const walk = (d) => {
    for (const name of readdirSync(d).sort()) {
      const full = join(d, name);
      if (statSync(full).isDirectory()) walk(full);
      else if (name.toLowerCase().endsWith(".png"))
        sizes["/" + full.replaceAll("\\", "/").replace(/^public\//, "")] =
          pngSize(full);
    }
  };
  walk(dir);
  return sizes;
}

if (
  process.argv[1]?.replaceAll("\\", "/").endsWith("scripts/image-sizes.mjs")
) {
  const sizes = collect();
  const rows = Object.entries(sizes)
    .map(([src, [w, h]]) => `  ${JSON.stringify(src)}: [${w}, ${h}],`)
    .join("\n");
  writeFileSync(
    OUT,
    `/**
 * Copyright (c) 2026 Yanis Sebastian Zürcher
 *
 * Generated by scripts/image-sizes.mjs (bun run images:sizes). Do not edit.
 * Pixel sizes of the project images, so a lazy <img> reserves its box.
 */

export const PROJECT_IMAGE_SIZES: Record<
  string,
  readonly [width: number, height: number]
> = {
${rows}
};
`,
  );
  console.log(`${OUT}: ${Object.keys(sizes).length} images`);
}
